name: hyprland_arch
description: Install and configure Hyprland on Arch Linux

depends_on:
  - waybar
  - hyprlock

steps:
  - name: install_hyprland
    script: |
      sudo pacman -S --noconfirm --needed hyprland swww

  - name: install_waypaper
    script: yay -S --noconfirm --needed waypaper

  - name: link_config
    script: |
      mkdir -p "$HOME/.config/hypr"
      ln -sf "$ROOT_DIR/config/hypr/hyprland.conf" "$HOME/.config/hypr/hyprland.conf"
      ln -sf "$ROOT_DIR/assets/default-background.jpg" "$HOME/.config/hypr/wallpaper.jpg"
