# frozen_string_literal: true

source 'https://rubygems.org'
gem 'brakeman'
gem 'lsp'
gem 'reek'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubocop-rails'
gem 'rubocop-rspec'
gem 'ruby-lsp'
gem 'ruby-lsp-rails'
gem 'test-prof'
