name: core_macos_install
description: Install base dependencies for macOS

steps:
  - name: install_homebrew
    install: |
      if ! command -v brew >/dev/null; then
        echo "🍺 Installing Homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      fi

  - name: install_basics
    install: brew install git curl yq
