name: zsh_macos
description: Install and configure Zsh with Oh My Zsh on macOS

steps:
  - name: install_zsh
    script: |
      log_verbose "📦 Installing..."
      brew install curl zsh

  - name: set_default_shell
    script: |
      log_verbose "🐚 Setting..."
      ZSH_PATH=$(command -v zsh || echo "/bin/zsh")
      chsh -s "$ZSH_PATH"
      echo "✅ Zsh set as default shell!"

  - name: install_oh_my_zsh
    script: |
      log_verbose "📦 Installing..."
      if [ ! -d "$HOME/.oh-my-zsh" ]; then
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
        echo "✅ Oh My Zsh installed successfully!"
      else
        echo "⚠️  Oh My Zsh is already installed!"
      fi

  - name: copy_themes
    script: |
      log_verbose "🎨 Updating..."
      THEME_DIR="$HOME/.oh-my-zsh/custom/themes"

      if [ -d "$ROOT_DIR/themes/zsh" ]; then
        for f in "$ROOT_DIR/themes/zsh/"*; do
          ln -sf "$f" "$THEME_DIR/$(basename "$f")"
        done
        echo "✅ Zsh themes updated successfully!"
      else
        echo "⚠️  No themes found to update."
      fi

  - name: link_config
    script: |
      log_verbose "📝 Linking..."
      ln -sf "$ROOT_DIR/config/zsh/zshrc" "$HOME/.zshrc"
      echo "✅ Zsh config linked successfully!"

  - name: link_aliases
    script: |
      log_verbose "📝 Linking..."
      ln -sf "$ROOT_DIR/config/zsh/aliases.zsh" "$HOME/.aliases.zsh"
      echo "✅ Zsh aliases linked successfully!"
