name: elixir
description: Install Elixir and Erlang via mise
depends_on:
  - mise

steps:
  - name: install_erlang
    script: |
      log_verbose "📦 Installing..."
      mise use -g erlang
      echo "✅ Erlang installed!"

  - name: install_elixir
    script: |
      log_verbose "📦 Installing..."
      mise use -g elixir
      echo "✅ Elixir installed!"
