# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
  exec tmux
fi

ZSH=$HOME/.oh-my-zsh

ZSH_THEME="obraun-custom"

plugins=(dotenv asdf vi-mode)

source $ZSH/oh-my-zsh.sh

# vi-mode plugin
VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true

# Bundle
alias be='bundle exec'

# OH
alias ohdcu='docker-compose -f ../overhaul-backend-local/docker-compose.development.yml up -d'
alias ohdcs='docker-compose -f ../overhaul-backend-local/docker-compose.development.yml stop'
alias ohdcp='docker-compose -f ../overhaul-backend-local/docker-compose.development.yml ps'

# Rubymine
alias minecd='nohup rubymine . &'

# Private
