# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
if [ "$TMUX" = "" ]; then tmux; fi

ZSH=$HOME/.oh-my-zsh

ZSH_THEME="crunch"

plugins=(dotenv)

source $ZSH/oh-my-zsh.sh

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"

SCRIPTS_PATH=$HOME/dotfiles/scripts

# aliases
# Scripts
alias load_tags=$SCRIPTS_PATH/load_tags.sh
alias cata=$SCRIPTS_PATH/cat_aliases.sh
alias fix_kb='sudo $SCRIPTS_PATH/fix_kb.sh'

#Docker
alias dce='docker-compose exec'
alias dcu='docker-compose up -d'
alias dcd='docker-compose down'
alias dps='docker ps'
alias dpsa='docker ps -a'

# Rails
alias be='bundle exec'
